### ISSUE TITLE
Add demos of using the tool in Juypter notebooks / Google Colabs

### ISSUE THREAD

**Issue by mithro** [AUCOHL/DFFRAM#130]
It would be great if DFFRAM examples and documentation was using Juypter Notebooks / Google Colabs to allow people to play with things extremely quickly.

@proppy has done a bunch of work to show this is totally possible;
 - https://twitter.com/proppy/status/1482036203428147203?s=20
 - https://twitter.com/proppy/status/1472768213381697540?s=20

You can then even add a "Launch in Colab" button / badge in the README...

**Comment by proppy** [comment]
one of the pre-requisite to this, is to get openlane and its dependencies to work well in https://colab.research.google.com/ which is not "trivial" in the current state of things because container don't really play well in the colab environment: https://github.com/googlecolab/colabtools/issues/299#issuecomment-615308778

this should be easier as we get more things packaged in conda:
https://github.com/hdl/conda-eda/pull/164
https://github.com/hdl/conda-eda/pull/165

**Comment by donn** [comment]
Done

**Comment by proppy** [comment]
Didn't realize this was being fixed with #143, added a few comments here https://github.com/Cloud-V/DFFRAM/pull/143#pullrequestreview-918290992 but let me know if you'd like me to send follow-up PRs to address them.
